version: "3"
services:
  master:
    container_name: jenkins_master
    image: jenkins/jenkins:2.277.1-lts-slim
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    links:
      - slave01

  slave01:
    container_name: jenkins_slave01
    image: jenkinsci/ssh-slave
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcZ5AcYvzdkSFHGbETFxetO7aFO7swlinsCIj/idRurD8dN7uqW7DvcJXZp06xO4uBwdxEeczcRjIwi3zos5b8jHhIijR5YnxWqbLyGvyJprBjg1Qounw9+8v2n0Hqiw5vONeBmHZ9Jt/hJjI5meTHmkD/b57omC64igDdqls1uy9mhegRJFXQi284gqNyhAmtf/pCvHMBSYzzCYgScwJpqSj5V3O3+BcQB/F0fw6kMxhtvQmId8S2jbihbIIpT7LxdnHWzl6WzqHzzXN7MqZqSEp8Hwga+m0hMiD/cp/zWXYByHEkHwAdBssU3HPOb6StTYA2QrOba+qTuJKyZf9r
