apiVersion: v1

# Kubernetesのリソースの種類を指定する属性 (ここではPodを指定)
kind: Pod

# リソースに付与するメタデータ
# metadata.nameで指定した値がこのリソースの名称となる
metadata:
  name: simple-echo

# specはリソースを定義するための属性
# Podの場合はPodを構成するコンテナ郡をcontainersとして定義する
spec:
  containers:
    - name: nginx
      image: gihyodocker/nginx-proxy:latest
      env:
        - name: BACKEND_HOST
          value: localhost:8080
      ports:
        - containerPort: 80
    - name: echo
      image: gihyodocker/echo:latest
      ports:
        - containerPort: 8080
